# Generated by Django 5.1.4 on 2025-01-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailoonapp', '0006_school'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='College',
        ),
    ]
