name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master  # Trigger the action when pushing to 'master' branch
  pull_request:
    branches:
      - master  # Trigger the action when a pull request is created targeting the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m venv env  # Create the virtual environment using 'env' as the name
          source env/bin/activate  # Activate the 'env' virtual environment
          pip install -r requirements.txt  # Install dependencies

      - name: Deploy to DigitalOcean
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Setup SSH for accessing the droplet
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan holanine.icu >> ~/.ssh/known_hosts  # Use your domain instead of the IP

          # SSH into the server and deploy the app
          ssh root@holanine.icu << EOF  # Use the domain name here
            # Navigate to your project directory
            cd /root/sailoonproject

            # Pull the latest code from GitHub
            git pull origin master  # Ensure it pulls from 'master' branch

            # Activate the existing virtual environment
            source /root/sailoonproject/env/bin/activate  # Ensure the 'env' is used

            # Install the latest dependencies
            pip install -r requirements.txt

            # Apply database migrations
            python manage.py migrate

            # Collect static files for production
            python manage.py collectstatic --noinput

            # Restart Gunicorn and Nginx to apply changes
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
