name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    
    # Setup Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Run Tests
    - name: Run Tests
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      # Deploy to DigitalOcean
      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            # Navigate to the project directory
            cd /home/root/sailoonproject/

            # Activate the virtual environment
            source /home/root/sailoonproject/env/bin/activate

            # Pull the latest changes from the master branch
            git pull origin master

            # Install any new dependencies
            pip install -r requirements.txt

            # Run migrations
            python manage.py migrate

            # Collect static files
            python manage.py collectstatic --noinput

            # Restart the app server (e.g., Gunicorn)
            systemctl restart gunicorn  # Adjust if you're using another app server like uWSGI
          EOF
